name: Sync CODEOWNERS to Spacewalk

# This workflow is triggered when code is pushed to the master branch,
# but only if the CODEOWNERS file or the sync script changes.
on:
  push:
    branches:
      - master
    paths:
      - '.github/CODEOWNERS'
      - '.github/scripts/sync_codeowners.sh'

jobs:
  sync:
    strategy:
      matrix:
        target_branch: [Manager-5.1, Manager-5.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout uyuni source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate an access token for spacewalk
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CODEOWNERS_SYNC_APP_ID }}
          private-key: ${{ secrets.CODEOWNERS_SYNC_PK }}
          repositories: spacewalk

      - name: Execute substitution script
        # Runs the script to substitute team names.
        # Output is saved to CODEOWNERS_spacewalk_temp
        run: bash .github/scripts/sync_codeowners.sh

      - name: Commit and push to temp branch for spacewalk/${{ matrix.target_branch }}
        run: |
            TARGET_ORG="cbbayburt"
            TARGET_REPO="spacewalk"
            TARGET_BRANCH="${{ matrix.target_branch }}"
            CLONE_DIR="spacewalk-checkout"
            SOURCE_FILE_NAME="CODEOWNERS_spacewalk_temp"
            TEMP_BRANCH="sync/${TARGET_BRANCH}-codeowners-$(date +%Y%m%d%H%M%S)"

            echo "Starting sync for branch: $TARGET_BRANCH"

            # Clone Spacewalk Repository using the token for write access
            # The IAT is short-lived and only has 'Contents' and 'Pull Requests' scopes
            TOKEN="${{ steps.generate_token.outputs.token }}"
            git clone -b $TARGET_BRANCH https://x-access-token:$TOKEN@github.com/$TARGET_ORG/$TARGET_REPO.git $CLONE_DIR
            cd $CLONE_DIR

            git config user.name "GitHub Action Bot"
            git config user.email "github-actions-bot@users.noreply.github.com"

            cp ../$SOURCE_FILE_NAME .github/CODEOWNERS

            if git diff --quiet .github/CODEOWNERS; then
              echo "No changes detected in CODEOWNERS. Skipping commit."
              cd ..
              rm -rf $CLONE_DIR
              exit 0
            fi

            echo "Changes detected. Committing and pushing to $TEMP_BRANCH..."

            git checkout -b $TEMP_BRANCH
            git add .github/CODEOWNERS
            git commit -m "chore(sync): Sync CODEOWNERS from uyuni-project/uyuni"
            git push -u origin $TEMP_BRANCH

            # Store branch names for next step (create PR)
            echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV

            cd ..
            rm -rf $CLONE_DIR

      - name: Create pull request for spacewalk/${{ matrix.target_branch }}
        if: success() && env.TEMP_BRANCH
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          title: "${{ env.TARGET_BRANCH }}:CODEOWNERS sync from uyuni repository"
          body: |
            This pull request was automatically generated to synchronize the CODEOWNERS file
            from the `uyuni-project/uyuni` repository to the `${{ env.TARGET_BRANCH }}` branch
            of the `SUSE/spacewalk` repository.
          branch: ${{ env.TEMP_BRANCH }}
          base: ${{ matrix.TARGET_BRANCH }}
